### PR TITLE
feat: support batch messages response

### PR DESCRIPTION
**Pull request by onhate**
1) support batch messages response
    use case: to send data and complete types on a single push request
    
    ```[{ id: "1", type: "data", ...  }, { id: "1", type: "complete" }]```

2) setup initial test structure and github actions

### CODE REVIEW

**Comment by onhate** [comment]
@lunchboxer I've added this feature although I know it's not described on the original spec but it adds value specially on serverless environments as it avoids an extra message to be sent to the client on each query request and it will speed up Promises resolution as it does not needs to wait an extra message to come to unsubscribe the query operation.

Also, I've setup an initial jest structure that we can evolve later.

**Comment by onhate** [comment]
Not sure why Github Actions are not running here, they were supposed to have run the tests

**Comment by onhate** [comment]
got it, it did run on my repository https://github.com/onhate/graphql-subscriptions-client/runs/1650356966?check_suite_focus=true but it was supposed to run on this one and to have added checks to the PR

**Comment by onhate** [comment]
@lunchboxer ?

**Comment by lunchboxer** [comment]
Very cool. Seems like you've added some functionality not present in subscriptions-transport-ws. In that case, could you add some concise documentation to the README?

**Comment by onhate** [comment]
sure yes, I'll push it soon

**Comment by onhate** [comment]
@lunchboxer done

**Pull request merged**
